### ISSUE TITLE
Error - bitmex.js

### ISSUE THREAD

**Issue by Tezeug** [DunnCreativeSS/marketmaker#2]
(node:7637) UnhandledPromiseRejectionWarning: Error: bitmex {"error":{"message":"orderQty is invalid","name":"HTTPError"}}
    at bitmex.handleErrors (/home/d7694/Desktop/D4/marketMaker/node_modules/ccxt/js/bitmex.js:600:31)
    at response.text.then (/home/d7694/Desktop/D4/marketMaker/node_modules/ccxt/js/base/Exchange.js:678:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:7637) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 129)

**Comment by nateflanders** [comment]
@Tezeug did you get this figured out? I'm getting the same issue. 

@DunnCreativeSS are you still supporting this at all?

**Comment by staccDOTsol** [comment]
@nateflanders  @Tezeug this is one of my older bots, it was only used on testnet/livenet with the deribit flavor.. that said, there's fake taker volume on testnets and the results at the time (before they limited position size to 100k) were 600+ BTC on 10 initial in 2-3 days.... where on livenet there wasn't nearly as much taker volume before the price would move and it would hold a bad position and lose all of it's gains, and more. We put 1+ BTC into the deribit livenet version and lost it :(

Feel free to join us here: https://t.me/ManyVolumeSignalMonster
